name: Post welcome comment
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo files
        id: echo_glob
        run: |
          shopt -s globstar
          FILELIST=($(ls **/tes*.xml))
          echo "file-list=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${FILELIST[@]}")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: List Files
        run: echo "${{join(fromJSON(steps.echo_glob.outputs.file-list))}}"
      
      - name: Upload Project Structure w/ Resolved Staging Resources as an Artifact
        uses: actions/upload-artifact@v3
        with:
          path: 'test'

